config/routes.rb
Fileupload::Application.routes.draw do
	match "/upload" => "upload#index", :as => :upload_index
	match "/upload/save" => "upload#save", :as => :upload_save

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
	def index
	end

	def save
		params[:Filedata].content_type = 
			MIME::Types.type_for(params[:Filedata].original_filename).to_s
		logger.info "Got a file: #{params.inspect}"

		render :json => { "status" => "success" }
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fileupload</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/upload/index.html.erb
<% session_key_name = Rails.application.config.session_options[:key] -%>

<script type="text/javascript">
$(function() {
	$("#file_upload").uploadify({
		uploader: '/assets/uploadify.swf',
		script: '<%= upload_save_url %>',
		fileDataName: "Filedata",
		cancelImg: "/images/cancel.png",
		fileDesc: "gimma sum filz",
		fileExt: "*.*",
		auto: false,
		sizeLimit: <%= 100.megabytes %>,
		width: 150,
		height: 25,
		multi: true, 
		wmode: "transparent",
		buttonText: "Uplode",
		removeCompleted: false,
		onComplete: function(a, b, c, response) {},
		scriptData: {
			"_http_accept" : "application/javascript",
			"_method" : "put",
			"<%= session_key_name %>" : encodeURIComponent("<%= u cookies[:key] %>"),
			"<%= request_forgery_protection_token %>" : encodeURIComponent("<%= u form_authenticity_token %>")
		},
		onSelectOnce: function(event,data) { alert("starting a file" + data); },
	});
});
</script>

<%= form_tag(upload_save_url, :multipart => true) do -%>
	<input id="file_upload" name="file_upload" type="file" />
	<a href="javascript:$('#file_upload').uploadifyUpload()">Upload Files</a>
<% end -%>